# This is a basic workflow to help you get started with Actions

name: GitOps

on: push

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          cluster_name: "sandbox"

      - name: Test
        run: |
          kubectl cluster-info
          kubectl apply -f ./argo-setup/kind.yaml
          sleep 30
          kubectl apply -f ./argo-setup/cert-issuer.yaml
          sleep 30
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          sleep 30
          
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          sleep 30
          kubectl apply -f ./argo-setup/ingress.yaml
          kubectl get pods --all-namespaces

