# This is a basic workflow to help you get started with Actions

name: GitOps

on: push

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          cluster_name: "sandbox"

      - name: Test
        run: |
          kubectl cluster-info
          kubectl run httpd --image=httpd
